language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby-19mode
  - ruby-head
matrix:
  allow_failures:
    rvm:
      - ruby-head
      - jruby-19mode
branches:
  only:
    - master
    - develop
